---
- name: Install php
  apt: 
    pkg: 
      - php
      - php-cli
      - php-curl
      - php-fileinfo
      - php-intl
      - openssl
      - php-mbstring
      - php-mysql
      - php-simplexml
      - composer

- name: Download symfony install script
  get_url:
    url: 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh'
    dest: /tmp/setup.deb.sh
    mode: '744'

- name: Run install script
  #become: true
  shell: /tmp/setup.deb.sh
  args:
    executable: /bin/bash
    
- name: Install symfony-cli
  apt:
    pkg:
    - symfony-cli
